### ISSUE TITLE
Missing TestExecution.json

### ISSUE THREAD

**Issue by jiriveselythermofishercom** [reqnroll/Reqnroll#198] opened 2024-07-02 12:43 UTC
### Reqnroll Version

2.0.3

### Which test runner are you using?

NUnit

### Test Runner Version Number

3.14.0

### .NET Implementation

.NET 8.0

### Test Execution Method

Command line – PLEASE SPECIFY THE FULL COMMAND LINE

### Content of reqnroll.json configuration file

{
    "$schema": "https://schemas.reqnroll.net/reqnroll-config-latest.json",
    
    "bindingAssemblies": [
    ]
}

### Issue Description

I can not find related tests output file "TestExecution.json".
Command line:
dotnet test --filter Category=DSLSimulationInstrument

### Steps to Reproduce

I ran related test but no TestExecution.json file was created.

**Comment by gasparnagy** [comment] 2024-07-02 13:28
Unfortunately SpecFlow.Plus.LivingDoc is a closed-source SpecFlow plugin without a public API, so Reqnroll cannot work with it.

Our plan is to rewrite it from scratch, see https://github.com/orgs/reqnroll/discussions/37.

Also see more details at #195 

I close this issue as by design now.

**Closed by gasparnagy** 2024-07-02 13:28 UTC
Labels: by design
