### ISSUE TITLE
Potentially wrong version number when attempting to find System.CodeDom?

### ISSUE THREAD

**Issue by user93485938459** [reqnroll/Reqnroll#282] opened 2024-10-06 19:32 UTC
### Reqnroll Version

2.1.0

### Which test runner are you using?

NUnit

### Test Runner Version Number

nunit: 4.2.2
nunit3testadapter: 4.6.0

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Content of reqnroll.json configuration file

```
{
  "reqnroll": {
    "stepArguments": {
      "convertToParameters": true,
      "paramNameRegex": "^Parameter$",
      "paramValueRegex": "^Value$"
    }
  },
  "NRetrySettings": {
    "maxRetries": 3,
    "applyGlobally": true
  }
}
```

### Issue Description

Having issues when build runs GenerateFeatureFileCodeBehindTask (.nuget\packages\reqnroll.tools.msbuild.generation\2.1.0\build\Reqnroll.Tools.MsBuild.Generation.targets) 
with the nunit retry package (NUnitRetry.ReqnrollPlugin), I'm now thinking it may be related to MsBuild.Generation instead so logging this.

Have also logged it in the retry package repo (https://github.com/chrisbillson/NUnitRetry.ReqnrollPlugin/issues/7) but I'm not sure it is directly the cause, although removing it from nuget does fix this issue. I don't know lol

I believe it may be pointing to the wrong version of System.CodeDom

It's looking for version 8.0.0.0 but the version on nuget is 8.0.0

```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	MSB4018	The "GenerateFeatureFileCodeBehindTask" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'System.CodeDom, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.CodeDom, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at NUnitRetry.ReqnrollPlugin.RetryGeneratorPlugin.CustomiseDependencies(Object sender, CustomizeDependenciesEventArgs eventArgs)
   at Reqnroll.Generator.GeneratorContainerBuilder.CreateContainer(ReqnrollConfigurationHolder configurationHolder, ProjectSettings projectSettings, IEnumerable`1 generatorPluginInfos, IObjectContainer parentObjectContainer)
   at Reqnroll.Tools.MsBuild.Generation.WrappedGeneratorContainerBuilder.BuildGeneratorContainer(ReqnrollConfigurationHolder reqnrollConfigurationHolder, ProjectSettings projectSettings, IReadOnlyCollection`1 generatorPluginInfos, IObjectContainer rootObjectContainer)
   at Reqnroll.Tools.MsBuild.Generation.GenerateFeatureFileCodeBehindTaskExecutor.Execute()
   at Reqnroll.Tools.MsBuild.Generation.GenerateFeatureFileCodeBehindTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
C:\Users\user\.nuget\packages\reqnroll.tools.msbuild.generation\2.1.0\build\Reqnroll.Tools.MsBuild.Generation.targets	93	
```
```
    <GenerateFeatureFileCodeBehindTask
      ProjectPath="$(MSBuildProjectFullPath)"
      OutputPath="$(ReqnrollCodeBehindOutputPath)"
      FeatureFiles="@(ReqnrollFeatureFiles)"
      RootNamespace="$(RootNamespace)"
      GeneratorPlugins="@(ReqnrollGeneratorPlugins)" 
      
      MSBuildVersion="$(MSBuildVersion)"
      AssemblyName="$(AssemblyName)"
      TargetFrameworks="$(Reqnroll_TargetFrameworks)"
      TargetFramework="$(Reqnroll_TargetFramework)"
      ProjectGuid="$(ProjectGuid)"
      >

      <Output TaskParameter="GeneratedFiles" ItemName="ReqnrollGeneratedFiles" />
    </GenerateFeatureFileCodeBehindTask>
```
### Steps to Reproduce

Install Reqnroll.NUnit, System.CodeDom 8.0.0, nunit3testadapter, nunit and NUnitRetry.ReqnrollPlugin. 

Then try to build with fresh feature file.

**Comment by gasparnagy** [comment] 2024-10-08 11:44
This is a duplicate of #244, so closing this one now.

I will attempt to make a release right now, to have this fix delivered.

**Closed by gasparnagy** 2024-10-08 11:44 UTC
Labels: duplicate
