### ISSUE TITLE
Unable to resolve IReqnrollOutputHelper and ITestThreadExecutionEventPublisher in BeforeTestRun hook

### ISSUE THREAD

**Issue by gmrozikmedius** [reqnroll/Reqnroll#189] opened 2024-06-21 11:15 UTC
### Reqnroll Version

2.0.3

### Which test runner are you using?

NUnit

### Test Runner Version Number

2.0.3

### .NET Implementation

.NET 8.0

### Test Execution Method

ReSharper Test Runner

### Issue Description

In the scope of this https://github.com/reqnroll/Reqnroll/pull/59, the way how dependencies in BeforeTestRun are resolved has changed.

I have two BeforeTestRun hooks implemented:
- logging some configuration entries to make troubleshooting easier
- attaching performance monitor

```
using Reqnroll;
using Reqnroll.Events;

namespace reqnroll_203;

[Binding]
public class Hooks
{
    [BeforeTestRun]
    public static void LogSomething(IReqnrollOutputHelper logger)
    {
        logger.WriteLine("test");
    }

    [BeforeTestRun]
    public static void AttachPerfLogger(TestThreadContext testThreadContext)
    {
        var events = testThreadContext.TestThreadContainer.Resolve<ITestThreadExecutionEventPublisher>();
        events.AddListener(new StepsPerformanceLogger());
    }
}
```

These hooks work fine in version 1.0.1, after migration to 2.0.3 I got exception like

```
OneTimeSetUp: Reqnroll.BoDi.ObjectContainerException : Interface cannot be resolved: Reqnroll.IReqnrollOutputHelper
   at Reqnroll.BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1()
   at Reqnroll.BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath, TimeSpan timeout)
   at Reqnroll.BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at Reqnroll.BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at Reqnroll.BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at Reqnroll.BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at Reqnroll.BoDi.ObjectContainer.Resolve(Type typeToResolve, String name)
   at Reqnroll.Infrastructure.TestObjectResolver.ResolveBindingInstance(Type bindingType, IObjectContainer container)
   at Reqnroll.Infrastructure.TestExecutionEngine.ResolveArgument(IObjectContainer container, IBindingParameter parameter)
   at Reqnroll.Infrastructure.TestExecutionEngine.<>c__DisplayClass54_0.<ResolveArguments>b__0(IBindingParameter p)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Reqnroll.Infrastructure.TestExecutionEngine.ResolveArguments(IHookBinding hookBinding, IObjectContainer currentContainer)
   at Reqnroll.Infrastructure.TestExecutionEngine.InvokeHookAsync(IAsyncBindingInvoker invoker, IHookBinding hookBinding, HookType hookType)
   at Reqnroll.Infrastructure.TestExecutionEngine.FireEventsAsync(HookType hookType)
   at Reqnroll.Infrastructure.TestExecutionEngine.FireEventsAsync(HookType hookType)
   at Reqnroll.Infrastructure.TestExecutionEngine.OnTestRunStartAsync()
   at Reqnroll.TestRunner.OnTestRunStartAsync()
   at Reqnroll.TestRunnerManager.FireTestRunStartAsync()
   at Reqnroll.TestRunnerManager.OnTestRunStartAsync(Assembly testAssembly, String testWorkerId, IContainerBuilder containerBuilder)
   at reqnroll_203_NUnitAssemblyHooks.AssemblyInitializeAsync() in C:\dev\reqnroll_test\reqnroll_203\obj\Debug\net8.0\NUnit.AssemblyHooks.cs:line 18
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.OneTimeSetUpCommand.<>c__DisplayClass0_0.<.ctor>b__0(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeTestCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeTestCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp()
```

Is there any way to resolve these two components in BeforeTestRun hook in version 2.0.3?

### Steps to Reproduce

- implement any simple test
- add following hook

```
[Binding]
public class Hooks
{
    [BeforeTestRun]
    public static void LogSomething(IReqnrollOutputHelper logger)
    {
        logger.WriteLine("test");
    }

    [BeforeTestRun]
    public static void AttachPerfLogger(TestThreadContext testThreadContext)
    {
        var events = testThreadContext.TestThreadContainer.Resolve<ITestThreadExecutionEventPublisher>();
        events.AddListener(new StepsPerformanceLogger());
    }
}
```

test is RED in 2.0.3, test is green in 1.0.1

**Comment by RicardoLans** [comment] 2024-06-24 08:15
I have a similar issue, but I'm using below workaround:

```csharp
[BeforeTestRun(Order = 0)]
public static void RegisterOutputHelper(IObjectContainer objectContainer, IReqnrollOutputHelper outputHelper)
{
    objectContainer.RegisterInstanceAs(outputHelper, typeof(IReqnrollOutputHelper));
}
```

**Comment by gmrozikmedius** [comment] 2024-06-24 09:23
@RicardoLans , your code won't work in 2.0.3.

**Comment by gasparnagy** [comment] 2024-06-24 12:54
Thank you for submitting this. This issue raises a couple of interesting questions.

The Before/AfterTestRun hooks "logically" run outside of the test-threads therefore any infrastructure that is only available for test-threads are generally not available in these hooks. 

Technically there IS a test-thread created for running these hooks, but this only an internal implementation detail.

There was a bug (#58) in SpecFlow v4 (and also in Reqnroll v1) that "provided" this internal test-thread container to resolve the dependencies of the Before/AfterTestRun hooks, that is why the codes above (incorrectly) worked. 

So based on that the issue should be considered as "by design". But there are workarounds, see below.

There are some interesting questions though that I cannot answer:

1. Why the `ITestThreadExecutionEventPublisher` is bound to a test-thread? Especially if it allows subscribing to the Before/AfterTestRun hooks as well. I don't know too much about this class and it is not documented, so I would think this is more like an "internal" class. 
2. Should we keep the test-thread allocated for running the Before/AfterTestRun hooks internal? Is there any danger in exposing it to the users in some way?

The state of `IReqnrollOutputHelper` is a bit different, because that typically (depends on the test runner) "forwards" the messages to the output-emitting interface of the test runners itself. But these interfaces are only available during execution of tests, so it is acceptable that `IReqnrollOutputHelper` is not available for Before/AfterTestRun hooks. 

To help finding the right solution, please @RicardoLans, @gmrozikmedius help with describing a bit more your context: What exactly do you want to achieve by accessing these classes from a Before/AfterTestRun hook?

## Workaround: 

You can use the following workaround to achieve a similar behavior:

```
[Binding]
public class SubscribeHooks {

  private static int _wasSubscribed = 0;
  
  [BeforeScenario(Order = -1000)] // make sure it runs first
  public void AddListener(ITestThreadExecutionEventPublisher publisher) {
    if (Interlocked.CompareExchange(ref _wasSubscribed, 1, 0) == 0) {
      publisher.AddListener(new StepsPerformanceLogger());
    }
  }
}
```

**Comment by RicardoLans** [comment] 2024-07-09 06:17
@gasparnagy my apologies for this very late reply, the `IReqnrollOutputHelper` is currently being used by me to simply see on test failure what hooks have been called and in what order in the test output. Just to quickly pinpoint if test failure comes from any hook. We have quite some hooks to setup our test environment, but as you pointed out since `IReqnrollOutputHelper` is not available in Before/AfterTestRun hooks I will just remove output logging from those hooks. Maybe I need to rewrite our test project since we have quite some BeforeTestRun hooks :)

**Comment by gasparnagy** [comment] 2024-07-09 10:58
@RicardoLans Thx for the feedback. With the workaround I have mentioned you can move in the "before run" logic to the test execution time (of the first test), where logging is already available and will be visible in the test report.

I will close this issue for now, because it is yet unclear how concretely Reqnroll could better support your situations. If you or @gmrozikmedius have any concrete suggestion, please feel free to reopen it.

**Closed by gasparnagy** 2024-07-09 10:58 UTC
Labels: by design
