### ISSUE TITLE
.feature.cs is not getting cleared when we clean the solution

### ISSUE THREAD

**Issue by sampath-ganesan** [reqnroll/Reqnroll#296] opened 2024-10-16 05:51 UTC
### Reqnroll Version

2.1.1

### Which test runner are you using?

MSTest

### Test Runner Version Number

3.6.0

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Issue Description

when i build solution then i will be able to to see test in test explorer, but when i clean the solution .feature.cs files are not getting cleared which results all the are showing in the test explorer

### Steps to Reproduce

1. use reqnroll in UI automation project
2. build that project
3. run some scenario
4. clean the project
5. it should clear the results with the .feature.cs file 
6. but its clearing the test results not the feature.cs

**Comment by gasparnagy** [comment] 2024-10-16 07:15
This is by design. We never intended to do that.

If you think this would we a useful feature, please start a new topic in the "Ideas" section of the discussion board: https://github.com/orgs/reqnroll/discussions/categories/ideas

Please also explain why this would be beneficial for you.

I'm closing this issue as "by design".

**Closed by gasparnagy** 2024-10-16 07:15 UTC
Labels: by design
