### ISSUE TITLE
Ambiguous steps found when using features in the Dutch language

### ISSUE THREAD

**Issue by mcd1976** [reqnroll/Reqnroll#218] opened 2024-07-24 13:36 UTC
### Reqnroll Version

2.0.3

### Which test runner are you using?

MSTest

### Test Runner Version Number

2.2.10

### .NET Implementation

.NET Framework 4.6.2 or later

### Test Execution Method

Visual Studio Test Explorer

### Content of reqnroll.json configuration file

{
  "$schema": "https://schemas.reqnroll.net/reqnroll-config-latest.json",
  "language": {
    "feature": "nl-NL",
    "binding": "nl-NL"
  },
  "bindingAssemblies": [
    {
      "assembly": "SharedUITesting.Specflow"
    }
  ]
}

### Issue Description

If we use the Dutch language for the feature files then the scoping of a particular class with the bindings to a particular feature no longer works. When using the English language then there is no issue.

### Steps to Reproduce

- Create multiple feature files in the Dutch language with some steps
- Create a binding class for each feature and scope it to each feature with the Scope attribute
- Let each class have a step method/binding with the same name
- The feature file will then complain about ambiguous steps.

Example Binding attribute;
[Binding, Scope(Tag = "Blog", Feature = "Blog")]

If we then rewrite the feature to English the issue is instantly gone without changing the binding classes.

**Comment by gasparnagy** [comment] 2024-07-26 13:27
I could not reproduce this. See attached a simple project with 2 feature files and scoped steps according to your description. It works for me.

[ReqnrollCalculator.Specs.zip](https://github.com/user-attachments/files/16392317/ReqnrollCalculator.Specs.zip)

I close this issue for now, please reopen if you have found any special circumstance that can play a role here. Please also include a simple repro project.

**Closed by gasparnagy** 2024-07-26 13:27 UTC
Labels: cannot reproduce
