### ISSUE TITLE
 maxParallelThreads is not limiting threads to number

### ISSUE THREAD

**Issue by saggy7001** [reqnroll/Reqnroll#219] opened 2024-07-26 11:06 UTC
### Reqnroll Version

2.0.3

### Which test runner are you using?

xUnit

### Test Runner Version Number

2.8.2

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Content of reqnroll.json configuration file

NA

### Issue Description

Tried both ways 
1. xunit.runner.json
`{
  "$schema": "https://xunit.net/schema/current/xunit.runner.schema.json",
  "maxParallelThreads": 14,
  "parallelAlgorithm": "aggressive",
  "parallelizeTestCollections": true
}
`
2. [assembly: CollectionBehavior(DisableTestParallelization = false, MaxParallelThreads = 4)]

Test Explorer starts too many threads and test fails 
I want to run test in max Parallel Threads 

### Steps to Reproduce

Try running test in parallel with more than 1 thread 

### Link to Repro Project

Reqnroll.xUnit

**Comment by gasparnagy** [comment] 2024-07-26 13:12
I could not reproduce this. See attached a simple project with 4 scenarios. Both has a simple wait step that waits for 5 seconds. Depending on what I set in the `AssemblyAttributes.cs` file (copied your attribute) I can see the maximum parallel threads being limited. 

[CleanReqnrollProject.Net8.XunitFw.zip](https://github.com/user-attachments/files/16392167/CleanReqnrollProject.Net8.XunitFw.zip)

In general, Reqnroll just generates standard xUnit source code, so we cannot really influence the execution strategy of xUnit.

I close this issue for now, please reopen if you have found any special circumstance that can play a role here. Please also include a simple repro project.

**Closed by gasparnagy** 2024-07-26 13:12 UTC
Labels: cannot reproduce
